version: "3.3"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=guifler
      - POSTGRES_PASSWORD=102030
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres    


  app:
    build: .
    container_name: rentx
    restart: always
    ports: 
      - 5656:3333
    volumes: 
      - .:/usr/app
    links:
      - database_ignite
    depends_on: 
      - database_ignite


volumes:
  pgdata:
    driver: local